// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.Horoscope
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("color")]
        public string Color { get; set; }

        [JsonProperty("compatibility")]
        public string[] Compatibility { get; set; }

        [JsonProperty("horoscope")]
        public string Horoscope { get; set; }

        [JsonProperty("luckyNumber")]
        public long LuckyNumber { get; set; }

        [JsonProperty("luckyTime")]
        public string LuckyTime { get; set; }

        [JsonProperty("mood")]
        public string Mood { get; set; }

        [JsonProperty("sign")]
        public string Sign { get; set; }

        [JsonProperty("zodiac")]
        public Zodiac Zodiac { get; set; }
    }

    public partial class Zodiac
    {
        [JsonProperty("element")]
        public string Element { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("stone")]
        public string Stone { get; set; }

        [JsonProperty("symbol")]
        public string Symbol { get; set; }
    }
}
